using Microsoft.Data.Sqlite;
using OpenAI;
using OpenAI.Chat;
using OpenAI.Embeddings;
using System.ClientModel;

namespace Rlzz.HazPro.RagSys.Services;

/// <summary>
/// let’s create the logic to generate, register and retrieve the embeddings, as well as formulate the response generated by the model.
/// </summary>
public class PolicyService
{
    private readonly ChatClient _chatClient;
    private readonly EmbeddingClient _embeddingClient;
    private readonly string _policyPath;
    private readonly string _dbPath;
    
    public PolicyService(IConfiguration config)
    {
        var apiKey = config["OpenAI:ApiKey"];
        var apiUrl = config["OpenAI:ApiUrl"];
        
        if (string.IsNullOrWhiteSpace(apiKey))
            throw new InvalidOperationException("Missing OpenAI:ApiKey in configuration.");

        var chatOptions = new OpenAIClientOptions();
        if (!string.IsNullOrWhiteSpace(apiUrl))
            chatOptions.Endpoint = new Uri(apiUrl);

        _chatClient = new OpenAIClient(new ApiKeyCredential(apiKey), chatOptions).GetChatClient("auto");
        _embeddingClient = new OpenAIClient(apiKey).GetEmbeddingClient("text-embedding-3-small");
        
        _policyPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "return_policy.txt");
        _dbPath = Path.Combine(Directory.GetCurrentDirectory(), "Data", "embeddings.db");

        InitializeDatabase();
        LoadPolicyIntoDatabaseAsync().Wait();
    }

    /// <summary>
    /// reads the content of the return policy file, generates the embeddings and saves them to the database for later use
    /// responsible for loading the policy content and saving its embeddings to the database
    /// <![CDATA[
    /// First, it reads the entire content of the policy file, located at _policyPath, and then divides it into smaller parts using the SplitIntoChunks() method.
    /// This division is important because OpenAI’s language models have input size limits.
    /// Therefore, the text is broken into blocks of up to 500 characters or tokens.
    ///
    /// Then, a new connection to the database is opened, and each text segment (chunk) is processed.
    /// For each segment, it checks if the content is already stored in the table.
    /// This is done through a query that counts how many records have the same text.
    /// If the segment already exists, it is ignored to avoid duplication
    ///
    /// When a new segment is found, the method requests the OpenAI embeddings model to generate a numerical vector representing the meaning of that text.
    /// The result is then converted to a float array, which is then transformed into bytes using the FloatArrayToBytes() method,
    /// to be compatible with the BLOB type of the database.
    ///
    /// Finally, the vector and the text are inserted together into the PolicyChunks table.
    /// ]]>
    /// </summary>
    private async Task LoadPolicyIntoDatabaseAsync()
    {
        var policyText = await File.ReadAllTextAsync(_policyPath);
        var chunks = SplitIntoChunks(policyText, 500);
        
        using var conn = new SqliteConnection($"Data Source={_dbPath}");
        conn.Open();

        foreach (var chunk in chunks)
        {
            var checkCmd = conn.CreateCommand();
            checkCmd.CommandText = "SELECT COUNT(*) FROM PolicyChunks WHERE Text = $text";
            checkCmd.Parameters.AddWithValue("$text", chunk);
            
            bool exists = Convert.ToInt32(checkCmd.ExecuteScalar()) > 0;
            if(exists) continue;

            try
            {
                var embeddingResult = await _embeddingClient.GenerateEmbeddingAsync(chunk);
                float[] vector = embeddingResult.Value.ToFloats().ToArray();
                
                var insertCmd = conn.CreateCommand();
                insertCmd.CommandText = "INSERT INTO PolicyChunks (Text, Embedding) VALUES ($text, $embedding)";
                insertCmd.Parameters.AddWithValue("$text", chunk);
                insertCmd.Parameters.AddWithValue("$embedding", FloatArrayToBytes(vector));
                
                insertCmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }
    }

    private static byte[] FloatArrayToBytes(float[] array)
    {
        var bytes = new byte[array.Length * sizeof(float)];
        Buffer.BlockCopy(array, 0, bytes, 0, bytes.Length);
        return bytes;
    }

    private static float[] BytesToFloatArray(byte[] bytes)
    {
        var floats = new float[bytes.Length / sizeof(float)];
    
        Buffer.BlockCopy(bytes, 0, floats, 0, bytes.Length);
        return floats;
    }
    
    private static double CosineSimilarity(float[] v1, float[] v2)
    {
        double dot = 0.0, mag1 = 0.0, mag2 = 0.0;
        for (int i = 0; i < v1.Length; i++)
        {
            dot += v1[i] * v2[i];
            mag1 += v1[i] * v1[i];
            mag2 += v2[i] * v2[i];
        }
        return dot / (Math.Sqrt(mag1) * Math.Sqrt(mag2));
    }
    
    private List<string> GetTopChunks(float[] queryEmbedding, int topN)
    {
        using var conn = new SqliteConnection($"Data Source={_dbPath}");
        conn.Open();

        var selectCmd = conn.CreateCommand();

        selectCmd.CommandText = "SELECT Text, Embedding FROM PolicyChunks";
   
        using var reader = selectCmd.ExecuteReader();

        var scoredChunks = new List<(string Text, double Score)>();
    
        while (reader.Read())
        {
            var text = reader.GetString(0);
            var embeddingBytes = (byte[])reader["Embedding"];
            var embedding = BytesToFloatArray(embeddingBytes);

            var similarity = CosineSimilarity(embedding, queryEmbedding);
            scoredChunks.Add((text, similarity));
        }

        return scoredChunks
            .OrderByDescending(x => x.Score)
            .Take(topN)
            .Select(x => x.Text)
            .ToList();
    }
    
    /// <summary>
    /// This method receives the user’s question and returns an AI-generated answer based on the policy content stored in the database.
    /// <![CDATA[
    /// First, it transforms the question into an embedding vector, using the same embedding model configured previously.
    /// This numerical vector (queryVector) represents the semantic meaning of the question.
    ///
    /// Next, the method calls GetTopChunks(), which searches the database for the chunks most similar to the meaning of the question, i.e.,
    /// the parts of the policy that contain information relevant to the answer.
    /// It requests the three most relevant chunks (topChunks),
    /// and then combines these texts into a single string called context.
    ///
    /// 
    /// ]]>
    /// </summary>
    /// <param name="question"></param>
    /// <returns></returns>
    public async Task<string> GetAnswerAsync(string question)
    {
        var queryEmbedding = await _embeddingClient.GenerateEmbeddingAsync(question);
        var queryVector = queryEmbedding.Value.ToFloats().ToArray();

        var topChunks = GetTopChunks(queryVector, 3);

        var context = string.Join("\n\n", topChunks);

        List<ChatMessage> messages = new()
        {
            ChatMessage.CreateSystemMessage("You are a helpful assistant that answers based on company return policies."),
            ChatMessage.CreateUserMessage($"Use only the following policy text to answer the question:\n\n{context}\n\nQuestion: {question}")
        };

        var response = await _chatClient.CompleteChatAsync(messages);
        return response.Value.Content[0].Text.Trim();
    }

    /// <summary>
    /// Split text into max 500 char
    /// </summary>
    /// <param name="text"></param>
    /// <param name="maxLength"></param>
    /// <returns></returns>
    private static IEnumerable<string> SplitIntoChunks(string text, int maxLength)
    {
        for (int i = 0; i < text.Length; i += maxLength)
            yield return text.Substring(i, Math.Min(maxLength, text.Length - i));
    }

    /// <summary>
    /// prepare the SQLite database, creating the necessary tables if they do not already exist,
    /// </summary>
    private void InitializeDatabase()
    {
        using var conn = new SqliteConnection($"Data Source={_dbPath}");
        conn.Open();

        var cmd = conn.CreateCommand();
        cmd.CommandText = @"CREATE TABLE IF NOT EXISTS PolicyChunks (
                        Id INTEGER PRIMARY KEY AUTOINCREMENT,
                        Text TEXT NOT NULL,
                        Embedding BLOB NOT NULL
                        );";
        cmd.ExecuteNonQuery();
    }
}